# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

benchmarking:
  enable: false

  processing:
    unit_conversion:
      TWh: 1000000
      GWh: 1000
      MWh: 1
      GW: 1000
      MW: 1
      kW: 0.001
