# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

benchmarking:
  enable: false

  processing:
    unit_conversion:
      TWh: 1000000
      GWh: 1000
      MWh: 1
      GW: 1000
      MW: 1
      kW: 0.001

  # Define default values for each table type
  table_types:
    scenario_comparison:
      index_col: [2, 3]  # TODO Document this as Excel-like index, starting at 1
      header: 4  # TODO Document this as Excel-like index, starting at 1
      plot: bar  # bar, area, None
    time_series:
      index_col: 1
      header: 4
      plot: area

  # Define table specific values
  tables:   # TODO Specify mandatory and optional fields
    final_energy_demand:
      table_type: scenario_comparison
      sheet_name: 5-
      unit: TWh
      index_col: 2
      header: [4, 5]
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        AC: electricity
        AC_OH: electricity
        H2: hydrogen
        gas: methane
        low voltage: electricity
        oil: liquids
        coal: solids

    elec_demand:
      table_type: scenario_comparison
      sheet_name: 52-
      unit: TWh
      index_col: 2
      header: [4, 5]
      names:
        index:
        - carrier
        column:
        - year
        - scenario
      mapping:
        H2 Electrolysis: others
        methanolisation: others
        electricity: residential

    methane_demand:
      table_type: scenario_comparison
      sheet_name: 53-
      unit: TWh
      names:
        index:
        - year
        - scenario
        column:
        - carrier
      mapping:
        CCGT: transformation input
        OCGT: transformation input
        SMR: transformation input
        SMR CC: transformation input
        gas for industry: industry
        gas for industry CC: industry

    hydrogen_demand:
      table_type: scenario_comparison
      sheet_name: 54-
      unit: TWh
      names:
        index:
        - year
        - scenario
        column:
        - carrier
      mapping:
        Fischer-Tropsch: e-fuels production
        H2 for industry: industry
        H2 turbine: electricity generation and heat production
        Sabatier: e-fuels production
        methanolisation: e-fuels production
        H2 for shipping: international shipping

    power_capacity:
      table_type: scenario_comparison
      sheet_name: 25-
      unit: GW
      nrows: 10
      ncolumns: 17
      names:
        index:
        - scenario
        - year
        column:
        - carrier
      mapping:
        offwind-dc-fl-r: wind offshore
        offwind-dc-fl-oh: wind offshore
        offwind-dc-fb-r: wind offshore
        offwind-dc-fb-oh: wind offshore
        offwind-ac-fl-r: wind offshore
        offwind-ac-fb-r: wind offshore
        onwind: wind onshore
        solar rooftop: solar
        solar-hsat: solar
        H2 turbine: hydrogen
        coal: coal + other fossil
        lignite: coal + other fossil
        CCGT: methane
        OCGT: methane
        battery discharger: battery
        home battery discharger: battery
        urban central solid biomass CHP: chp and small thermal
        PHS: hydro and pumped storage
        hydro: hydro and pumped storage
        ror: hydro and pumped storage


    power_generation:
      table_type: scenario_comparison
      sheet_name: 26-
      unit: TWh
      nrows: 10
      ncolumns: 16
      names:
        index:
        - scenario
        - year
        column:
        - carrier
      mapping:
        offwind-dc-fl-r: wind offshore
        offwind-dc-fl-oh: wind offshore
        offwind-dc-fb-r: wind offshore
        offwind-dc-fb-oh: wind offshore
        offwind-ac-fl-r: wind offshore
        offwind-ac-fb-r: wind offshore
        onwind: wind onshore
        solar rooftop: solar
        solar-hsat: solar
        H2 turbine: hydrogen
        coal: coal + other fossil
        lignite: coal + other fossil
        CCGT: methane
        OCGT: methane
        urban central solid biomass CHP: other non-res
        ror: hydro (exc. pump storage)
        hydro: hydro (exc. pump storage)

    methane_supply:
      table_type: scenario_comparison
      sheet_name: 32-
      unit: TWh
      index_col: 2
      header: [6, 7]
      nrows: 13
      ncolumns: 9
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        Sabatier: synthetic methane (domestic)
        biogas to gas: biomethane (domestic)
        gas: natural gas (import)

    hydrogen_supply:
      table_type: scenario_comparison
      sheet_name: 33-
      unit: TWh
      header: [4, 5]
      index_col: 2
      nrows: 13
      ncolumns: 9
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        H2 Electrolysis: p2g
        H2 import LH2: ammonia imports
        H2 import Pipeline: low carbon imports
        SMR: smr (grey)
        SMR CC: smr with ccs (blue)

    biomass_supply:
      table_type: scenario_comparison
      sheet_name: 59-
      unit: TWh
      index_col: 2
      header: [4, 5]
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        solid biomass: biomass

    energy_imports:
      table_type: scenario_comparison
      sheet_name: 60-
      unit: TWh
      index_col: 2
      header: [3, 4]
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        H2 import LH2: hydrogen
        H2 import Pipeline: hydrogen
        coal: solids
        lignite: solids
        oil refining: liquids

    generation_profiles:
      table_type: time_series
      sheet_name:
        DE: 30a
        GA: 30b
      unit: GW
      names:
        index:
        - snapshot
        column:
        - carrier
      mapping:
        offwind-dc-fl-r: offshore wind
        offwind-dc-fl-oh: offshore wind
        offwind-dc-fb-r: offshore wind
        offwind-dc-fb-oh: offshore wind
        offwind-ac-fl-r: offshore wind
        offwind-ac-fb-r: offshore wind
        onwind: onshore wind
        solar rooftop: solar
        solar-hsat: solar
        H2 turbine: methane&hydrogen
        CCGT: methane&hydrogen
        OCGT: methane&hydrogen
        coal: coal&lignite&oil
        lignite: coal&lignite&oil
        oil: coal&lignite&oil
        battery discharger: battery
        home battery discharger: battery
        urban central solid biomass CHP: other res
        PHS: hydro
        ror: hydro
