# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

benchmarking:
  enable: false
  remove_last_day: false
  spatial:
    by_bus: true
    by_country: true


  tables:
    power_capacity:
      table_type: scenario_comparison
      mapping_col: benchmarking_capacity
      rfc_sources:
      - dashboard_out
      - report
      unit: GW
      report:
        sheet_name: "57"
        index_col: 3
        header: 3
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year

    power_generation:
      table_type: scenario_comparison
      mapping_col: benchmarking_generation
      rfc_sources:
      - dashboard_out
      - report
      unit: TWh
      report:
        sheet_name: "58"
        index_col: 2
        header: 2
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year

    final_energy_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_fed
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: "4"
        index_col: 2
        header: 5
        scenario: NT+
        names:
          index:
          - year
          column:
          - carrier

    electricity_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_elec_demand
      rfc_sources:
      - dashboard_out
      - report
      unit: TWh
      report:
        sheet_name: "35"
        index_col: 3
        header: 4
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year

    electricity_prosumer_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_elec_demand
      rfc_sources:
      - dashboard_out
      unit: TWh

    methane_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_ch4_demand
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: "46"
        index_col: 3
        header: 4
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year

    hydrogen_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_h2_demand
      rfc_sources:
      - dashboard_out
      - report
      unit: TWh
      report:
        sheet_name: "41"
        index_col: 3
        header: 4
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year

    methane_supply:
      table_type: scenario_comparison
      mapping_col: benchmarking_ch4_supply
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: "70"
        index_col: [3, 4]
        header: 4
        nrows: 10
        scenario: NT+
        names:
          index:
          - origin
          - carrier
          column:
          - year

    hydrogen_supply:
      table_type: scenario_comparison
      mapping_col: benchmarking_h2_supply
      rfc_sources:
      - dashboard_out
      - report
      unit: TWh
      report:
        sheet_name: "74"
        index_col: 3
        header: 5
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year

    biomass_supply:
      table_type: scenario_comparison
      mapping_col: benchmarking_biomass_supply
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: "81"
        index_col: 2
        header: 4
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year
      biomass_to_methane_efficiency:
        # Values from TYNDP 2024 Supply Tool
        2030: 0.68
        2035: 0.68  # Interpolated
        2040: 0.68
        2045: 0.68  # Interpolated
        2050: 0.68
      biogas_not_upgraded:
        # Values from TYNDP 2024 Supply Tool, EU27, 8760h
        2030: 33  # TWh
        2035: 45
        2040: 56

    energy_imports:
      table_type: scenario_comparison
      mapping_col: benchmarking_energy_imports
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: "83"
        index_col: 2
        header: 3
        ncolumns: 7
        scenario: NT+
        names:
          index:
          - carrier
          column:
          - year

    electricity_price:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - dashboard_out
      unit: EUR/MWh_e

    electricity_price_excl_shed:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - dashboard_out
      unit: EUR/MWh_e
      exclude_coupling_effects: true  # If true, derive threshold from VOLL EUR/MWh_H2 × electrolysis efficiency

    hydrogen_price:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - dashboard_out
      unit: EUR/MWh_H2

    hydrogen_price_excl_shed:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - dashboard_out
      unit: EUR/MWh_H2
      exclude_coupling_effects: true  # If true, derive threshold from VOLL EUR/MWh_e × H2-CCGT efficiency

    crossborder_electricity:
      table_type: flows
      rfc_sources:
      - dashboard_out
      unit: MWh

    crossborder_hydrogen:
      table_type: flows
      rfc_sources:
      - dashboard_out
      unit: MWh

    electricity_demand_shedding_hours:
      table_type: hours
      mapping_col: benchmarking_shed_hours
      rfc_sources:
      - dashboard_out
      unit: hours

    hydrogen_demand_shedding_hours:
      table_type: hours
      mapping_col: benchmarking_shed_hours
      rfc_sources:
      - dashboard_out
      unit: hours
