# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: "dev"
  name: all
  scenarios:
    enable: true
    file: config/scenarios.tyndp.yaml

scenario:
  clusters:
  - 55

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'CY', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK']

electricity:
  base_network: tyndp-raw

transmission_projects:
  enable: true
  include:
    tyndp2020: false
    nep: false
    manual: false