# SPDX-FileCopyrightText: : 2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "test"
  disable_progressbar: true

# TODO set foresight
foresight: myopic

scenario:
  ll:
  - v1.0
  clusters:
  - 100
  planning_horizons:
  - 2030

# TODO check countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

snapshots:
  # TODO define multiple climatic years, being either 1995 2008 or 2009
  start: "2013-01-01"
  end: "2014-01-01"

enable:
  retrieve_tyndp_bundle: true

co2_budget:
  # TODO define carbon budget compliant with EU 2030 and 2050 targets
  2020: 0.701
  2025: 0.524
  2030: 0.297
  2035: 0.150
  2040: 0.071
  2045: 0.032
  2050: 0.000

transmission_projects:
  # TODO set TYNDP projects
  enable: true
  include:
    tyndp2020: true
    nep: true
    manual: true
load:
  source: tyndp # opsd, tyndp
  tyndp_scenario:
    scenario: DE  # NT, DE or GA
    year: 2030  # 2030, 2040 or 2050 (only for DE or GA)

pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror
  StorageUnit:
  - PHS
  - hydro
  Store: []

sector:
  transport: true
  heating: true
  biomass: false
  industry: false
  agriculture: false
  fossil_fuels: true

  land_transport_fuel_cell_share:  # Not modelled
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  land_transport_electric_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.45
    2040: 0.7
    2045: 0.85
    2050: 1
  land_transport_ice_share:  # Not modelled
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0

clustering:
  temporal:
    resolution_sector: 50SEG
