# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: "tyndp"

# TODO set foresight
foresight: overnight

scenario:
  clusters:
  - all
  planning_horizons:
  - 2030
  - 2040

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'CY', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK']

snapshots:
  # TODO define multiple climatic years, being either 1995 2008 or 2009
  start: "2013-01-01"
  end: "2014-01-01"

enable:
  retrieve_tyndp_bundle: true

co2_budget:
  # TODO define carbon budget compliant with EU 2030 and 2050 targets
  2020: 0.701
  2025: 0.524
  2030: 0.297
  2035: 0.150
  2040: 0.071
  2045: 0.032
  2050: 0.000

electricity:
  base_network: tyndp-raw
  transmission_limit: v1.0

links:
  p_max_pu: 1.0
  p_min_pu: 0

transmission_projects:
  enable: true
  include:
    tyndp2020: false
    nep: false
    manual: false

pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror
  StorageUnit:
  - PHS
  - hydro
  Store: []

sector:
  transport: false
  heating: true
  biomass: true
  industry: true
  shipping: false
  aviation: false
  agriculture: false
  fossil_fuels: true

  land_transport_fuel_cell_share:  # Not modelled
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  land_transport_electric_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.45
    2040: 0.7
    2045: 0.85
    2050: 1
  land_transport_ice_share:  # Not modelled
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  h2_topology_tyndp:
    enable: true
    tyndp_scenario: DE  # NT, DE or GA
  ATR: false
  hydrogen_fuel_cell: false
  hydrogen_turbine: true
  transmission_efficiency:
    enable:
    - gas pipeline
    - electricity distribution grid
  imports:
    enable: true
    carriers:
    - H2

clustering:
  mode: administrative  # TODO Switch to Bidding zones to preserve bidding zones shapes
  administrative:
    level: 3
  temporal:
    resolution_sector: 6H
