# yaml-language-server: $schema=schema.default.json
# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

# Use this file by setting --config data_config=tyndp

data:
  hotmaps_industrial_sites:
    source: ot-archive
    version: latest
  enspreso_biomass:
    source: ot-archive
    version: latest
  osm:
    source: ot-archive
    version: latest
  worldbank_urban_population:
    source: ot-archive
    version: latest
  worldbank_commodity_prices:
    source: ot-archive
    version: latest
  gem_europe_gas_tracker:
    source: ot-archive
    version: latest
  gem_gcct:
    source: ot-archive
    version: latest
  instrat_co2_prices:
    source: primary
    version: latest
  co2stop:
    source: ot-archive
    version: latest
  nitrogen_statistics:
    source: ot-archive
    version: latest
  eu_nuts2013:
    source: ot-archive
    version: latest
  eu_nuts2021:
    source: ot-archive
    version: latest
  eurostat_balances:
    source: ot-archive
    version: latest
  eurostat_household_balances:
    source: ot-archive
    version: latest
  wdpa:
    source: archive
    version: latest
  wdpa_marine:
    source: archive
    version: latest
  luisa_land_cover:
    source: ot-archive
    version: latest
  jrc_idees:
    source: ot-archive
    version: latest
  scigrid_gas:
    source: ot-archive
    version: latest
  seawater_temperature:
    source: ot-archive
    version: latest
  swiss_energy_balances:
    source: primary
    version: latest
  synthetic_electricity_demand:
    source: ot-archive
    version: latest
  opsd_electricity_demand:
    source: ot-archive
    version: latest
  entsoe_electricity_demand:
    source: ot-archive
    version: latest
  neso_electricity_demand:
    source: ot-archive
    version: latest
  copernicus_land_cover:
    source: ot-archive
    version: latest
  ship_raster:
    source: ot-archive
    version: latest
  eez:
    source: ot-archive
    version: latest
  nuts3_population:
    source: ot-archive
    version: latest
  gdp_per_capita:
    source: ot-archive
    version: latest
  population_count:
    source: ot-archive
    version: latest
  ghg_emissions:
    source: ot-archive
    version: latest
  gebco:
    source: ot-archive
    version: latest
  attributed_ports:
    source: ot-archive
    version: latest
  corine:
    source: ot-archive
    version: latest
  emobility:
    source: ot-archive
    version: latest
  h2_salt_caverns:
    source: ot-archive
    version: latest
  lau_regions:
    source: ot-archive
    version: latest
  aquifer_data:
    source: ot-archive
    version: latest
  osm_boundaries:
    source: ot-archive
    version: latest
  gem_gspt:
    source: ot-archive
    version: latest
  tyndp:
    source: ot-archive
    version: latest
  powerplants:
    source: ot-archive
    version: latest
  costs:
    source: ot-archive
    version: latest
  country_runoff:
    source: ot-archive
    version: latest
  country_hdd:
    source: ot-archive
    version: latest
  natura:
    source: ot-archive
    version: latest
  bfs_road_vehicle_stock:
    source: primary
    version: latest
  bfs_gdp_and_population:
    source: primary
    version: latest
  mobility_profiles:
    source: ot-archive
    version: latest
  cutout:
    source: archive
    version: latest
  dh_areas:
    source: ot-archive
    version: latest
  geothermal_heat_utilisation_potentials:
    source: ot-archive
    version: latest
  jrc_ardeco:
    source: ot-archive
    version: latest
  bidding_zones_electricitymaps:
    source: ot-archive
    version: latest
  bidding_zones_entsoepy:
    source: ot-archive
    version: latest
  tyndp_pecd:
    source: ot-archive
    version: latest
  tyndp_vis_plfm:
    source: ot-archive
    version: latest
  tyndp_cba_projects:
    source: ot-archive
    version: latest
  tyndp_nuclear_profiles:
    source: ot-archive
    version: latest
  tyndp_cba_non_co2_emissions:
    source: ot-archive
    version: latest
  cba_guidelines_reference_projects:
    source: ot-archive
    version: latest
  open_tyndp_prelim:
    source: archive
    version: latest
