# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: MIT


# NT Scenario - Defined in config/config.tyndp.yaml
NT:
  tyndp_scenario: NT


NT-ws1995:
#  <<: *cba-common
  snapshots:
    start: "1995-01-01"
    end: "1996-01-01"

  atlite:
    default_cutout: europe-1995-sarah3-era5

  cba:
    sb_scenario: NT


NT-ws2008:
#  <<: *cba-common
  snapshots:
    start: "2008-01-01"
    end: "2009-01-01"

  atlite:
    default_cutout: europe-2008-sarah3-era5

  cba:
    sb_scenario: NT


NT-ws2009:
#  <<: *cba-common
  snapshots:
    start: "2009-01-01"
    end: "2010-01-01"

  atlite:
    default_cutout: europe-2009-sarah3-era5

  cba:
    sb_scenario: NT


NT-wscenarios:
  cba:
    scenarios: [NT-ws2009, NT-ws2008, NT-ws1995]
