# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: MIT


# NT Scenario - Defined in config/config.tyndp.yaml
NT:
  tyndp_scenario: NT

# HEV: same inputs as NT, with fuel and CO2 prices +10% (TYNDP 2026 Scenarios Methodology Report, ch. 10, p. 65)
HEV:
  tyndp_scenario: HEV
  costs:
    custom_cost_scn: HEV
    emission_prices:
      co2:
        # NT values x 1.1 
        2030: 107.22
        2035: 217.26
        2040: 327.29
        2050: 553.01

# LEV: same inputs as NT, with fuel and CO2 prices -10% (TYNDP 2026 Scenarios Methodology Report, ch. 10, p. 65)
LEV:
  tyndp_scenario: LEV
  costs:
    custom_cost_scn: LEV
    emission_prices:
      co2:
        # NT values x 0.9
        2030: 87.72
        2035: 177.76
        2040: 267.79
        2050: 452.47

NT-ws1995:
#  <<: *cba-common
  snapshots:
    start: "1995-01-01"
    end: "1996-01-01"

  atlite:
    default_cutout: europe-1995-sarah3-era5

  cba:
    sb_scenario: NT


NT-ws2008:
#  <<: *cba-common
  snapshots:
    start: "2008-01-01"
    end: "2009-01-01"

  atlite:
    default_cutout: europe-2008-sarah3-era5

  cba:
    sb_scenario: NT


NT-ws2009:
#  <<: *cba-common
  snapshots:
    start: "2009-01-01"
    end: "2010-01-01"

  atlite:
    default_cutout: europe-2009-sarah3-era5

  cba:
    sb_scenario: NT


NT-wscenarios:
  cba:
    scenarios: [NT-ws2009, NT-ws2008, NT-ws1995]
